# Generated by Django 3.2 on 2022-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxassessordata',
            name='id',
        ),
        migrations.AddField(
            model_name='taxassessordata',
            name='apn',
            field=models.CharField(default='DELETE ME', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxassessordata',
            name='current_sales_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taxassessordata',
            name='basement_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taxassessordata',
            name='row_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxassessordata',
            name='use_code',
            field=models.CharField(help_text='https://data.sfgov.org/Housing-and-Buildings/Reference-Assessor-Recorder-Property-Class-Codes/pa56-ek2h', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='taxassessordata',
            name='year_property_built',
            field=models.IntegerField(null=True),
        ),
    ]
