# Generated by Django 3.2 on 2022-03-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20220305_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxassessordata',
            name='property_location',
            field=models.TextField(default='DELETE ME'),
            preserve_default=False,
        ),
    ]
