# Generated by Django 3.2 on 2022-03-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_taxassessordata_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('global_id', models.UUIDField()),
                ('apn', models.CharField(max_length=12)),
                ('geometry', models.TextField()),
                ('mblr', models.CharField(max_length=15)),
                ('zone', models.IntegerField(choices=[(1, 'Page St'), (2, 'Duboce Culdesacs'), (3, 'East Of Duboce'), (4, 'East Hill'), (5, 'Duboce Triangle Best'), (6, 'North Buena Vista'), (7, 'Alamo Square'), (8, 'Oak And Fell'), (9, 'Duboce Triangle Rest'), (10, 'Ashbury Heights'), (11, 'Nopa'), (12, 'North Corona Heights'), (13, 'Haight St'), (14, 'East Of Alamo'), (15, 'Corona Heights'), (16, 'North Mission')])),
            ],
            options={
                'unique_together': {('global_id', 'zone')},
            },
        ),
    ]
