# Generated by Django 3.2 on 2022-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_neighborhoodbuildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('apn', models.CharField(max_length=12)),
                ('owner_name', models.TextField()),
                ('owner_1_full_name', models.TextField()),
                ('owner_2_full_name', models.TextField(null=True)),
                ('do_not_mail', models.BooleanField()),
                ('site_address', models.TextField()),
                ('mailing_address', models.TextField()),
                ('legal_description', models.TextField(null=True)),
                ('lot_sqft', models.IntegerField()),
                ('total_sqft', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('total_stories', models.FloatField()),
                ('comm_num_units', models.IntegerField(null=True)),
                ('res_full_baths', models.IntegerField()),
                ('res_half_baths', models.IntegerField()),
                ('parking_count', models.IntegerField(null=True)),
                ('parking_sqft', models.IntegerField(null=True)),
                ('parking_desc', models.CharField(max_length=20, null=True)),
                ('improvement_value', models.IntegerField()),
                ('land_value', models.IntegerField()),
                ('total_assessed_value', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('ot_sale_date', models.DateField(null=True)),
                ('ot_sale_price', models.IntegerField(null=True)),
                ('ot_deed_type', models.CharField(max_length=32, null=True)),
                ('ot_sale_recording_date', models.DateField(null=True)),
                ('market_sale_date', models.DateField(null=True)),
                ('market_sale_price', models.IntegerField(null=True)),
                ('market_sale_recording_date', models.DateField(null=True)),
                ('prior_sale_date', models.DateField(null=True)),
                ('prior_sale_price', models.IntegerField(null=True)),
                ('prior_sale_recording_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
