# Generated by Django 3.2 on 2022-03-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='res_half_baths',
            field=models.IntegerField(null=True),
        ),
    ]
