# Generated by Django 3.2 on 2022-03-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_alter_owners_res_half_baths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='ot_deed_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
