# Generated by Django 3.2 on 2022-03-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_alter_owners_ot_deed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='total_stories',
            field=models.FloatField(null=True),
        ),
    ]
