# Generated by Django 3.2 on 2022-03-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_alter_owners_total_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='parking_desc',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
