# Generated by Django 3.2 on 2022-03-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_alter_owners_parking_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='mailing_address',
            field=models.TextField(null=True),
        ),
    ]
