# Generated by Django 3.2 on 2022-03-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_alter_owners_mailing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='improvement_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='land_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='lot_sqft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='res_full_baths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='tax_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='total_assessed_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='total_sqft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='year_built',
            field=models.IntegerField(null=True),
        ),
    ]
