# Generated by Django 3.2 on 2022-03-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_auto_20220306_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='owner_1_full_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='owners',
            name='owner_name',
            field=models.TextField(null=True),
        ),
    ]
