# Generated by Django 3.2 on 2022-03-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_auto_20220306_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='site_address',
            field=models.TextField(null=True),
        ),
    ]
