# Generated by Django 3.2 on 2022-03-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_alter_owners_site_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZillowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apn', models.CharField(max_length=12)),
                ('block', models.CharField(max_length=6)),
                ('lot', models.CharField(max_length=6)),
                ('zillow_url', models.TextField(null=True)),
                ('zestimate', models.IntegerField(null=True)),
                ('rent_zestimate', models.IntegerField(null=True)),
                ('rent', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('baths', models.FloatField(null=True)),
                ('sqft', models.IntegerField(null=True)),
                ('time_scraped', models.DateTimeField(null=True)),
                ('price_history', models.JSONField(null=True)),
                ('Label', models.FloatField(help_text='0 means a rating was impossible because there were no pictures', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
