# Generated by Django 3.2 on 2022-03-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_zillowdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apn', models.CharField(max_length=12)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
