# Generated by Django 3.2 on 2022-03-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0017_auto_20220307_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='parcel_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
