# Generated by Django 3.2 on 2022-03-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0021_rename_label_rating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(help_text='1 through 10', null=True),
        ),
    ]
