# Generated by Django 3.2 on 2022-03-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0022_alter_rating_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorClassCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('use_code', models.CharField(max_length=4)),
                ('use_definition', models.TextField()),
                ('property_class_code', models.CharField(max_length=4)),
                ('property_class_definition', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(help_text='1 through 10, or None if not enough info to tell', null=True),
        ),
    ]
