# Generated by Django 3.2 on 2022-03-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_alter_rating_rater'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZillowAddresses',
            fields=[
                ('zillowsnapshot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.zillowsnapshot')),
            ],
            options={
                'db_table': 'zillow_addresses',
                'managed': False,
            },
            bases=('houses.zillowsnapshot',),
        ),
    ]
