# Generated by Django 4.0 on 2022-04-18 21:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0027_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
